### ISSUE TITLE
Blur quality

### ISSUE THREAD

**Issue by StashCat** [Xaymar/obs-stream-effects#21]
The blur effect requires too much processing power on higher radii. The best solution for this currently is downscaling the source, blurring the downscaled image and then scaling it back to original size. This can be implemented in a much more optimized fashion in the plugin itself by just discarding pixels selectively, reducing the amount of calculations and making the filter faster at a barely noticeable quality decrease.

**Comment by Xaymar** [comment]
This is technically outside of the scope of the plugin. If you need a faster way, I'd recommend doing exactly what you already said to do. However there are actual optimizations that can be done for the filter.

### Pass the Kernel by Value instead of Texture
Currently the plugin allocates a Kernel texture containing every kernel for 0 Width to 31 Width. This is very inefficient as Textures really don't fit well into a Fragment L1 cache. A significant speed up could already be attained through simply moving the values into an actual float array of constant size.

### Use the result of linear-sampling in addition to multi-pass blurring
The filter already uses dual-pass blurring, which is the only reason that Gaussian blur doesn't absolutely kill your GPU right now. The number of texture accesses can be halved if we take linear-sampling into account and do some clever math to hide the inaccuracies resulting from that.

### Unroll the loop
The D3D11 and OpenGL shader compilers currently don't know how many iterations the loop will do at most. This is inefficient and leads to expensive instructions being generated. This plus the first optimization is already a huge boost, looping code is very expensive.

### Implement better Blur filters
There are many solutions that actually out-perform currently implement solutions simply by their access pattern and how they actually calculate the final value. Some however are a bit difficult to actually do without direct access to D3D11 or the OpenGL api, which OBS abstracts away.

**Comment by Xaymar** [comment]
A faster variant of Box Blur is now implemented: Box Linear. This blur reduces the total number of samples by n, allowing the blur to run even faster. If the Radius is even, the blur only takes O(2n+1) instead of O(4n+1), if the Radius is odd, the blur only takes O(2n) instead of O(4n+1).

The same type of optimization will be added for Gaussian Blur, in addition to moving to kernel array instead of texture.

**Comment by Xaymar** [comment]
Gaussian Linear Blur has also now been implemented, reducing the number of samples for Gaussian Blur by up to n. An even radius will now only take O(2n+2), while an odd radius will take O(2n+4) instead of O(4n+2). Further improvements can be done by switching out the kernel texture with an array of floats.

**Comment by Xaymar** [comment]
Gaussian Blur now also has the kernel array optimization, further reducing GPU usage. This is as far as I'll optimize this for now, and should make Gaussian Blur more usable.

Marking as Fixed/Completed.
