### ISSUE TITLE
How do I make it show up in filters?

### ISSUE THREAD

**Issue by Nitebytes** [Xaymar/obs-stream-effects#51]
**Describe the bug**
I installed from the exe (ver 0.4.2.215) , pointed it at C:\Program Files (x86)\obs-studio and let it run.
I ran OBS Studio (v21.1.0) right clicked video source for filters, but the plugin filters were not there, just the default ones.

Thinking there was an issue with the .exe I downloaded the zip and extracted it to C:\Program Files (x86)\obs-studio, it promnpted me to overwrite the files already existing, so the installer had put everything in the right place.

Started OBS Studio again and still no blur.

What did I do wrong?

Thanks

**Comment by Xaymar** [comment]
Please upload the last log file created after installing the plugin.

**Comment by TalonGrayson** [comment]
Hi,

I'm having a similar problem, but I installed by overwriting the files from the .zip

Closed OBS

Extracted the files in the zip to `C:\Program Files (x86)\obs-studio` - e.g.:
`C:\Program Files (x86)\obs-studio\obs-plugins\64bit\obs-stream-effects.dll`
`C:\Program Files (x86)\obs-studio\obs-plugins\64bit\obs-stream-effects.pdb`

Relaunched OBS

No entries in the Filters. Which is odd, since I was previously using 3D Transform filters (not sure which version I was running)

**Comment by Xaymar** [comment]
Again, please upload the last log file. Without a log file, no further help can be provided.

**Comment by Nitebytes** [comment]
[2019-03-24 17-51-05.txt](https://github.com/Xaymar/obs-stream-effects/files/3000644/2019-03-24.17-51-05.txt)

Log file from post-install of the pack

**Comment by Xaymar** [comment]
Version 0.5.0 and above need at least OBS Studio 22.x or newer. Only Version 0.4.2 supports OBS Studio 21.x

**Comment by Nitebytes** [comment]
I didn't realise there was a newer version, thanks.
I'm on v21.1 of OBS studio and 0.4.2.215 of this, so it _should_ work, right?

**Comment by Xaymar** [comment]
0.4.2 is 0.4.2.0. 0.5.0pr3 is 0.4.2.215. The last number is the build since the last release.

Version 0.5.0 is available to Patrons on [my Patreon](https://patreon.com/Xaymar) and has been announced at the start of the month through most social media channels. It is in early access until the end of the month, but it's likely that 0.6.0 will be released to Patrons before then.

**Comment by Nitebytes** [comment]
OK, downloaded the latest OBS and now I have blur. Thanks :)
